
services:
  web:
    build: 
      context: ./startup_planner_backend
      dockerfile: Dockerfile
    command: sh -c "python manage.py migrate &&
           python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./startup_planner_backend:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - ./startup_planner_backend/.env.staging
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./db.env
    ports:
      - "5432:5432"

volumes:
  postgres_data:

