

import DashboardNav from "@/components/dashboard/navbar"
import { Bricolage_Grotesque } from 'next/font/google'
import { Syne } from 'next/font/google'
import { cn } from '@/lib/utils'
import Sidebar from "@/components/dashboard/sidebar"
import "../globals.css"
import MobileNav from "@/components/dashboard/mobile-nav"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const fontHeading = Bricolage_Grotesque({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-heading',
})

const fontBody = Syne({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-body',
})





export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          'antialiased',
          fontHeading.className,
        )}
      >
        <div className="flex min-h-screen w-full flex-col bg-muted/40">

          <DashboardNav />
          <MobileNav />

          <div className="flex flex-1 overflow-hidden">
            <Sidebar />

            <div className="flex flex-1 flex-col">
              {children}

            </div>
          </div>

        </div>
      </body>
    </html>
  );
}
