# Generated by Django 5.0.7 on 2024-07-09 18:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=4096, unique=True)),
                ('code_verifier', models.CharField(max_length=4096)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('canva_user_id', models.CharField(max_length=1024, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('team_id', models.CharField(blank=True, max_length=255, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('access_token', models.CharField(blank=True, max_length=4096, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=4096, null=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.URLField(blank=True, max_length=1024, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='custom_user_groups', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=19, validators=[django.core.validators.MinLengthValidator(13), django.core.validators.MaxLengthValidator(19), django.core.validators.RegexValidator(message='Card number must be numeric and between 13 and 19 digits', regex='^\\d{13,19}$')])),
                ('card_expiry', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Card expiry must be in MM/YY format', regex='^\\d{2}/\\d{2}$')])),
                ('card_cvc', models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(4), django.core.validators.RegexValidator(message='CVC must be numeric and 3 or 4 digits', regex='^\\d{3,4}$')])),
                ('card_zip', models.CharField(max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
