# Generated by Django 5.0.6 on 2024-07-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canva_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='canva_user_id',
            field=models.CharField(max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='oauthstate',
            name='code_verifier',
            field=models.CharField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='oauthstate',
            name='state',
            field=models.CharField(max_length=4096, unique=True),
        ),
    ]
