# Generated by Django 5.0.7 on 2024-07-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canva_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="canva_user_id",
            field=models.CharField(blank=True, max_length=1024, null=True, unique=True),
        ),
    ]
