# Generated by Django 5.0.6 on 2024-07-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canva_auth', '0002_alter_customuser_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthstate',
            name='code_verifier',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='oauthstate',
            name='state',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
