# Generated by Django 5.0.6 on 2024-07-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canva_auth', '0004_alter_customuser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
