# Generated by Django 5.0.7 on 2024-07-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='founding_date',
            field=models.DateField(blank=True, null=True, verbose_name='Founding Date'),
        ),
        migrations.AddField(
            model_name='business',
            name='funding_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Funding Amount'),
        ),
        migrations.AddField(
            model_name='business',
            name='long_description',
            field=models.TextField(blank=True, verbose_name='Long Description'),
        ),
        migrations.AddField(
            model_name='business',
            name='stage',
            field=models.CharField(choices=[('Idea', 'Idea'), ('MVP', 'MVP'), ('Growth', 'Growth'), ('Maturity', 'Maturity')], default='idea', max_length=20, verbose_name='Stage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='stage_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stage Description'),
        ),
        migrations.AddField(
            model_name='business',
            name='team_size',
            field=models.PositiveIntegerField(default=1, verbose_name='Team Size'),
        ),
    ]
