# Generated by Django 5.0.7 on 2024-07-27 22:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0002_business_founding_date_business_funding_amount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Competitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("industry", models.CharField(max_length=30, verbose_name="Industry")),
                ("product", models.CharField(max_length=50, verbose_name="Product")),
                (
                    "market_share",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Market Share",
                    ),
                ),
                ("website", models.URLField(verbose_name="Website")),
                (
                    "customer_reviews",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Customer Reviews"
                    ),
                ),
                (
                    "growth_trend",
                    models.CharField(
                        choices=[
                            ("Steady", "Steady"),
                            ("Decreasing", "Decreasing"),
                            ("Increasing", "Increasing"),
                        ],
                        max_length=10,
                        verbose_name="Growth Trend",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competitors",
                        to="business.business",
                        verbose_name="Business",
                    ),
                ),
            ],
            options={
                "unique_together": {("business", "name")},
            },
        ),
        migrations.CreateModel(
            name="CompetitorStrength",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=100, verbose_name="Strength"),
                ),
                (
                    "competitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strengths",
                        to="business.competitor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompetitorWeakness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=100, verbose_name="Weakness"),
                ),
                (
                    "competitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weaknesses",
                        to="business.competitor",
                    ),
                ),
            ],
        ),
    ]
