# Generated by Django 5.0.7 on 2024-07-27 22:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0003_competitor_competitorstrength_competitorweakness"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competitor",
            name="industry",
            field=models.CharField(max_length=255, verbose_name="Industry"),
        ),
        migrations.AlterField(
            model_name="competitor",
            name="market_share",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator("0"),
                    django.core.validators.MaxValueValidator("100"),
                ],
                verbose_name="Market Share",
            ),
        ),
        migrations.AlterField(
            model_name="competitor",
            name="product",
            field=models.CharField(max_length=255, verbose_name="Product"),
        ),
    ]
