# Generated by Django 5.0.7 on 2024-07-28 07:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0004_alter_competitor_industry_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competitor",
            name="market_share",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
                verbose_name="Market Share",
            ),
        ),
    ]
