# Generated by Django 5.0.7 on 2024-08-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0005_alter_competitor_market_share"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="stage_description",
            field=models.TextField(blank=True, verbose_name="Stage Description"),
        ),
    ]
