import type { Metadata } from "next";
import { Bricolage_Grotesque } from 'next/font/google'
import { Syne } from 'next/font/google'
import { cn } from '@/lib/utils'
import '../globals.css'
import { Toaster } from "@/components/ui/toaster";
import Navbar from "@/components/landing-page/navbar";

const fontHeading = Bricolage_Grotesque({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-heading',
})

const fontBody = Syne({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-body',
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          'antialiased',
          fontHeading.className,
        )}
      >
        <Navbar />


        {children}
        <Toaster />
      </body>
    </html>
  );
}
